# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/demo/Documents/found

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/demo/Documents/found

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demo/Documents/found/CMakeFiles /home/demo/Documents/found//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demo/Documents/found/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named edge_detection

# Build rule for target.
edge_detection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edge_detection
.PHONY : edge_detection

# fast build rule for target.
edge_detection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_detection.dir/build.make CMakeFiles/edge_detection.dir/build
.PHONY : edge_detection/fast

#=============================================================================
# Target rules for targets named test_edge_detection

# Build rule for target.
test_edge_detection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_edge_detection
.PHONY : test_edge_detection

# fast build rule for target.
test_edge_detection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_edge_detection.dir/build.make CMakeFiles/test_edge_detection.dir/build
.PHONY : test_edge_detection/fast

src/edge_detection/simple-edge-detection.o: src/edge_detection/simple-edge-detection.cpp.o
.PHONY : src/edge_detection/simple-edge-detection.o

# target to build an object file
src/edge_detection/simple-edge-detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_detection.dir/build.make CMakeFiles/edge_detection.dir/src/edge_detection/simple-edge-detection.cpp.o
.PHONY : src/edge_detection/simple-edge-detection.cpp.o

src/edge_detection/simple-edge-detection.i: src/edge_detection/simple-edge-detection.cpp.i
.PHONY : src/edge_detection/simple-edge-detection.i

# target to preprocess a source file
src/edge_detection/simple-edge-detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_detection.dir/build.make CMakeFiles/edge_detection.dir/src/edge_detection/simple-edge-detection.cpp.i
.PHONY : src/edge_detection/simple-edge-detection.cpp.i

src/edge_detection/simple-edge-detection.s: src/edge_detection/simple-edge-detection.cpp.s
.PHONY : src/edge_detection/simple-edge-detection.s

# target to generate assembly for a file
src/edge_detection/simple-edge-detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/edge_detection.dir/build.make CMakeFiles/edge_detection.dir/src/edge_detection/simple-edge-detection.cpp.s
.PHONY : src/edge_detection/simple-edge-detection.cpp.s

test/edge_detection/test-simple-edge-detection.o: test/edge_detection/test-simple-edge-detection.cpp.o
.PHONY : test/edge_detection/test-simple-edge-detection.o

# target to build an object file
test/edge_detection/test-simple-edge-detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_edge_detection.dir/build.make CMakeFiles/test_edge_detection.dir/test/edge_detection/test-simple-edge-detection.cpp.o
.PHONY : test/edge_detection/test-simple-edge-detection.cpp.o

test/edge_detection/test-simple-edge-detection.i: test/edge_detection/test-simple-edge-detection.cpp.i
.PHONY : test/edge_detection/test-simple-edge-detection.i

# target to preprocess a source file
test/edge_detection/test-simple-edge-detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_edge_detection.dir/build.make CMakeFiles/test_edge_detection.dir/test/edge_detection/test-simple-edge-detection.cpp.i
.PHONY : test/edge_detection/test-simple-edge-detection.cpp.i

test/edge_detection/test-simple-edge-detection.s: test/edge_detection/test-simple-edge-detection.cpp.s
.PHONY : test/edge_detection/test-simple-edge-detection.s

# target to generate assembly for a file
test/edge_detection/test-simple-edge-detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_edge_detection.dir/build.make CMakeFiles/test_edge_detection.dir/test/edge_detection/test-simple-edge-detection.cpp.s
.PHONY : test/edge_detection/test-simple-edge-detection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... edge_detection"
	@echo "... test_edge_detection"
	@echo "... src/edge_detection/simple-edge-detection.o"
	@echo "... src/edge_detection/simple-edge-detection.i"
	@echo "... src/edge_detection/simple-edge-detection.s"
	@echo "... test/edge_detection/test-simple-edge-detection.o"
	@echo "... test/edge_detection/test-simple-edge-detection.i"
	@echo "... test/edge_detection/test-simple-edge-detection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

