var annotated_dup =
[
    [ "found", "namespacefound.html", [
      [ "_d_u_", "unionfound_1_1__d__u__.html", "unionfound_1_1__d__u__" ],
      [ "_f_u_", "unionfound_1_1__f__u__.html", "unionfound_1_1__f__u__" ],
      [ "Action", "classfound_1_1Action.html", "classfound_1_1Action" ],
      [ "ApproximateOrbitPropagationAlgorithm", "classfound_1_1ApproximateOrbitPropagationAlgorithm.html", "classfound_1_1ApproximateOrbitPropagationAlgorithm" ],
      [ "Attitude", "classfound_1_1Attitude.html", "classfound_1_1Attitude" ],
      [ "CalibrationAlgorithm", "classfound_1_1CalibrationAlgorithm.html", "classfound_1_1CalibrationAlgorithm" ],
      [ "CalibrationPipelineExecutor", "classfound_1_1CalibrationPipelineExecutor.html", "classfound_1_1CalibrationPipelineExecutor" ],
      [ "Camera", "classfound_1_1Camera.html", "classfound_1_1Camera" ],
      [ "Component", "structfound_1_1Component.html", "structfound_1_1Component" ],
      [ "DataFile", "structfound_1_1DataFile.html", "structfound_1_1DataFile" ],
      [ "DataFileHeader", "structfound_1_1DataFileHeader.html", "structfound_1_1DataFileHeader" ],
      [ "DateTime", "structfound_1_1DateTime.html", "structfound_1_1DateTime" ],
      [ "DistanceDeterminationAlgorithm", "classfound_1_1DistanceDeterminationAlgorithm.html", "classfound_1_1DistanceDeterminationAlgorithm" ],
      [ "DistancePipelineExecutor", "classfound_1_1DistancePipelineExecutor.html", "classfound_1_1DistancePipelineExecutor" ],
      [ "EarthSphericalVec3", "structfound_1_1EarthSphericalVec3.html", "structfound_1_1EarthSphericalVec3" ],
      [ "Edge", "structfound_1_1Edge.html", "structfound_1_1Edge" ],
      [ "EdgeDetectionAlgorithm", "classfound_1_1EdgeDetectionAlgorithm.html", null ],
      [ "EllipticDistanceDeterminationAlgorithm", "classfound_1_1EllipticDistanceDeterminationAlgorithm.html", "classfound_1_1EllipticDistanceDeterminationAlgorithm" ],
      [ "EulerAngles", "classfound_1_1EulerAngles.html", "classfound_1_1EulerAngles" ],
      [ "FeatureDetectionVectorGenerationAlgorithm", "classfound_1_1FeatureDetectionVectorGenerationAlgorithm.html", "classfound_1_1FeatureDetectionVectorGenerationAlgorithm" ],
      [ "Image", "structfound_1_1Image.html", "structfound_1_1Image" ],
      [ "LocationRecord", "structfound_1_1LocationRecord.html", "structfound_1_1LocationRecord" ],
      [ "LoCEdgeDetectionAlgorithm", "classfound_1_1LoCEdgeDetectionAlgorithm.html", "classfound_1_1LoCEdgeDetectionAlgorithm" ],
      [ "LOSTCalibrationAlgorithm", "classfound_1_1LOSTCalibrationAlgorithm.html", "classfound_1_1LOSTCalibrationAlgorithm" ],
      [ "LOSTVectorGenerationAlgorithm", "classfound_1_1LOSTVectorGenerationAlgorithm.html", "classfound_1_1LOSTVectorGenerationAlgorithm" ],
      [ "Mat3", "classfound_1_1Mat3.html", "classfound_1_1Mat3" ],
      [ "OrbitParams", "structfound_1_1OrbitParams.html", "structfound_1_1OrbitParams" ],
      [ "OrbitPipelineExecutor", "classfound_1_1OrbitPipelineExecutor.html", "classfound_1_1OrbitPipelineExecutor" ],
      [ "OrbitPropagationAlgorithm", "classfound_1_1OrbitPropagationAlgorithm.html", "classfound_1_1OrbitPropagationAlgorithm" ],
      [ "Pipeline", "classfound_1_1Pipeline.html", "classfound_1_1Pipeline" ],
      [ "PipelineExecutor", "classfound_1_1PipelineExecutor.html", "classfound_1_1PipelineExecutor" ],
      [ "Quaternion", "classfound_1_1Quaternion.html", "classfound_1_1Quaternion" ],
      [ "SimpleEdgeDetectionAlgorithm", "classfound_1_1SimpleEdgeDetectionAlgorithm.html", "classfound_1_1SimpleEdgeDetectionAlgorithm" ],
      [ "SphericalDistanceDeterminationAlgorithm", "classfound_1_1SphericalDistanceDeterminationAlgorithm.html", "classfound_1_1SphericalDistanceDeterminationAlgorithm" ],
      [ "Stage", "classfound_1_1Stage.html", "classfound_1_1Stage" ],
      [ "Vec2", "structfound_1_1Vec2.html", "structfound_1_1Vec2" ],
      [ "Vec3", "classfound_1_1Vec3.html", "classfound_1_1Vec3" ],
      [ "VectorGenerationAlgorithm", "classfound_1_1VectorGenerationAlgorithm.html", "classfound_1_1VectorGenerationAlgorithm" ]
    ] ],
    [ "CalibrationOptions", "classCalibrationOptions.html", null ],
    [ "DistanceOptions", "classDistanceOptions.html", null ],
    [ "OrbitOptions", "classOrbitOptions.html", null ]
];