var annotated_dup =
[
    [ "found", null, [
      [ "_d_u_", "unionfound_1_1__d__u__.html", "unionfound_1_1__d__u__" ],
      [ "_f_u_", "unionfound_1_1__f__u__.html", "unionfound_1_1__f__u__" ],
      [ "Action", "classfound_1_1Action.html", "classfound_1_1Action" ],
      [ "ApproximateOrbitPropagationAlgorithm", "classfound_1_1ApproximateOrbitPropagationAlgorithm.html", "classfound_1_1ApproximateOrbitPropagationAlgorithm" ],
      [ "CalibrationAlgorithm", "classfound_1_1CalibrationAlgorithm.html", null ],
      [ "CalibrationPipelineExecutor", "classfound_1_1CalibrationPipelineExecutor.html", "classfound_1_1CalibrationPipelineExecutor" ],
      [ "Camera", "classfound_1_1Camera.html", "classfound_1_1Camera" ],
      [ "Component", "structfound_1_1Component.html", "structfound_1_1Component" ],
      [ "DataFile", "structfound_1_1DataFile.html", "structfound_1_1DataFile" ],
      [ "DataFileHeader", "structfound_1_1DataFileHeader.html", "structfound_1_1DataFileHeader" ],
      [ "DateTime", "structfound_1_1DateTime.html", "structfound_1_1DateTime" ],
      [ "DistanceDeterminationAlgorithm", "classfound_1_1DistanceDeterminationAlgorithm.html", null ],
      [ "DistancePipelineExecutor", "classfound_1_1DistancePipelineExecutor.html", "classfound_1_1DistancePipelineExecutor" ],
      [ "EarthSphericalVec3", "structfound_1_1EarthSphericalVec3.html", "structfound_1_1EarthSphericalVec3" ],
      [ "Edge", "structfound_1_1Edge.html", "structfound_1_1Edge" ],
      [ "EdgeDetectionAlgorithm", "classfound_1_1EdgeDetectionAlgorithm.html", null ],
      [ "EllipticDistanceDeterminationAlgorithm", "classfound_1_1EllipticDistanceDeterminationAlgorithm.html", "classfound_1_1EllipticDistanceDeterminationAlgorithm" ],
      [ "FeatureDetectionVectorGenerationAlgorithm", "classfound_1_1FeatureDetectionVectorGenerationAlgorithm.html", "classfound_1_1FeatureDetectionVectorGenerationAlgorithm" ],
      [ "FunctionStage", "classfound_1_1FunctionStage.html", "classfound_1_1FunctionStage" ],
      [ "Image", "structfound_1_1Image.html", "structfound_1_1Image" ],
      [ "IterativeSphericalDistanceDeterminationAlgorithm", "classfound_1_1IterativeSphericalDistanceDeterminationAlgorithm.html", "classfound_1_1IterativeSphericalDistanceDeterminationAlgorithm" ],
      [ "LocationRecord", "structfound_1_1LocationRecord.html", "structfound_1_1LocationRecord" ],
      [ "LoGEdgeDetectionAlgorithm", "classfound_1_1LoGEdgeDetectionAlgorithm.html", "classfound_1_1LoGEdgeDetectionAlgorithm" ],
      [ "LOSTCalibrationAlgorithm", "classfound_1_1LOSTCalibrationAlgorithm.html", "classfound_1_1LOSTCalibrationAlgorithm" ],
      [ "LOSTVectorGenerationAlgorithm", "classfound_1_1LOSTVectorGenerationAlgorithm.html", "classfound_1_1LOSTVectorGenerationAlgorithm" ],
      [ "ModifyingPipeline", "classfound_1_1ModifyingPipeline.html", "classfound_1_1ModifyingPipeline" ],
      [ "ModifyingStage", "classfound_1_1ModifyingStage.html", "classfound_1_1ModifyingStage" ],
      [ "OrbitParams", "structfound_1_1OrbitParams.html", "structfound_1_1OrbitParams" ],
      [ "OrbitPipelineExecutor", "classfound_1_1OrbitPipelineExecutor.html", "classfound_1_1OrbitPipelineExecutor" ],
      [ "OrbitPropagationAlgorithm", "classfound_1_1OrbitPropagationAlgorithm.html", "classfound_1_1OrbitPropagationAlgorithm" ],
      [ "Pipeline", "classfound_1_1Pipeline.html", "classfound_1_1Pipeline" ],
      [ "PipelineExecutor", "classfound_1_1PipelineExecutor.html", "classfound_1_1PipelineExecutor" ],
      [ "SequentialPipeline", "classfound_1_1SequentialPipeline.html", "classfound_1_1SequentialPipeline" ],
      [ "SimpleEdgeDetectionAlgorithm", "classfound_1_1SimpleEdgeDetectionAlgorithm.html", "classfound_1_1SimpleEdgeDetectionAlgorithm" ],
      [ "SphericalDistanceDeterminationAlgorithm", "classfound_1_1SphericalDistanceDeterminationAlgorithm.html", "classfound_1_1SphericalDistanceDeterminationAlgorithm" ],
      [ "Stage", "classfound_1_1Stage.html", "classfound_1_1Stage" ],
      [ "VectorGenerationAlgorithm", "classfound_1_1VectorGenerationAlgorithm.html", null ]
    ] ],
    [ "CalibrationOptions", "classCalibrationOptions.html", null ],
    [ "DistanceOptions", "classDistanceOptions.html", null ],
    [ "OrbitOptions", "classOrbitOptions.html", null ]
];