version: "3.9"
services:
  dev:
    # emmulate intel amd64 on Apple Silicon for __float128 compatibility
    platform: linux/amd64     
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
