version: "3.9"
services:
  dev:
    platform: linux/amd64     # ✅ Now in the correct spot
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
