"""
FOUND File Analyzer Tool

This package provides utilities for analyzing .found files generated by the 
FOUND satellite positioning system. It can extract and display metadata,
position records, and verify file integrity.
"""

__version__ = "1.0.0"
