from src.preprocess.constructs.macros import DefineDirective

# Test expression strings
UNDEFINED_EXPR = "UNDEFINED"
DEFINED_EXPR = "defined(UNDEFINED)"
DEFINED_EXISTS_EXPR = "defined(EXISTS)"
NOT_TRUE_EXPR = "!TRUE"
NOT_FALSE_EXPR = "!FALSE"
BITWISE_NOT_ZERO_EXPR = "~ZERO"
BITWISE_NOT_ONE_EXPR = "~ONE"
PARENTHESES_EXPR = "(FIVE)"
ADDITION_EXPR = "ONE + ONE"
ZERO_ADDITION_EXPR = "ZERO + ZERO"
SUBTRACTION_EXPR = "FIVE - THREE"
ZERO_SUBTRACTION_EXPR = "THREE - THREE"
MULTIPLICATION_EXPR = "THREE * FOUR"
ZERO_MULTIPLICATION_EXPR = "FIVE * ZERO"
DIVISION_EXPR = "EIGHT / TWO"
DIVISION_ONE_EXPR = "SEVEN / SEVEN"
DIVISION_TWO_EXPR = "SEVEN / THREE"
MODULO_EXPR = "SEVEN % THREE"
ZERO_MODULO_EXPR = "SIX % THREE"
EQUALITY_TRUE_EXPR = "FIVE == FIVE"
EQUALITY_FALSE_EXPR = "FIVE == THREE"
INEQUALITY_TRUE_EXPR = "FIVE != THREE"
INEQUALITY_FALSE_EXPR = "FIVE != FIVE"
LESS_THAN_TRUE_EXPR = "THREE < FIVE"
LESS_THAN_FALSE_EXPR = "FIVE < THREE"
LESS_EQUAL_TRUE_EXPR = "THREE <= FIVE"
LESS_EQUAL_FALSE_EXPR = "FIVE <= THREE"
GREATER_THAN_TRUE_EXPR = "FIVE > THREE"
GREATER_THAN_FALSE_EXPR = "THREE > FIVE"
GREATER_EQUAL_TRUE_EXPR = "FIVE >= THREE"
GREATER_EQUAL_FALSE_EXPR = "THREE >= FIVE"
BITWISE_AND_NONZERO_EXPR = "FIVE & THREE"
BITWISE_AND_ZERO_EXPR = "FIVE & TWO"
BITWISE_OR_NONZERO_EXPR = "FIVE | THREE"
BITWISE_OR_SAME_EXPR = "FIVE | FIVE"
BITWISE_XOR_NONZERO_EXPR = "FIVE ^ THREE"
BITWISE_XOR_ZERO_EXPR = "FIVE ^ FIVE"
LEFT_SHIFT_NONZERO_EXPR = "THREE << TWO"
LEFT_SHIFT_ZERO_EXPR = "ZERO << THREE"
RIGHT_SHIFT_NONZERO_EXPR = "TWELVE >> TWO"
RIGHT_SHIFT_ZERO_EXPR = "THREE >> THREE"
LOGICAL_AND_TRUE_EXPR = "ONE && ONE"
LOGICAL_AND_FALSE_EXPR = "ONE && ZERO"
LOGICAL_OR_TRUE_EXPR = "ZERO || ONE"
LOGICAL_OR_FALSE_EXPR = "ZERO || ZERO"
COMPLEX_TRUE_EXPR = "A && (B > A)"
COMPLEX_FALSE_EXPR = "A && (B > A)"
PRECEDENCE_TRUE_EXPR = "ONE + TWO > TWO"
PRECEDENCE_FALSE_EXPR = "ONE + ONE > TWO"
RECURSIVE_EXPR = "A"

# Define directives
ZERO_MACRO = DefineDirective("ZERO", "0")
ONE_MACRO = DefineDirective("ONE", "1")
TWO_MACRO = DefineDirective("TWO", "2")
THREE_MACRO = DefineDirective("THREE", "3")
FOUR_MACRO = DefineDirective("FOUR", "4")
FIVE_MACRO = DefineDirective("FIVE", "5")
SIX_MACRO = DefineDirective("SIX", "6")
SEVEN_MACRO = DefineDirective("SEVEN", "7")
EIGHT_MACRO = DefineDirective("EIGHT", "8")
TWELVE_MACRO = DefineDirective("TWELVE", "12")
DEFINED_MACRO = DefineDirective("DEFINED", "1")
EXISTS_MACRO = DefineDirective("EXISTS", "1")
TRUE_MACRO = DefineDirective("TRUE", "1")
FALSE_MACRO = DefineDirective("FALSE", "0")
A_MACRO = DefineDirective("A", "1")
B_MACRO = DefineDirective("B", "2")
A_MACRO_2 = DefineDirective("A", "2")
B_MACRO_1 = DefineDirective("B", "1")
A_RECURSIVE = DefineDirective("A", "B")
B_RECURSIVE = DefineDirective("B", "5")