name: Build, Test, and Lint
on:
  push:
    branches: [ "refractor" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build all (Twice)
      run: (make compile || make compile)
  
  test:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v3
    - name: Test (Twice)
      run: (make test || make test)
  
  lint:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v3
    - name: Stylecheck
      run: make google_stylecheck
    - name: Test Stylecheck
      run: make google_stylecheck_test
    - name: Line Endings
      uses: erclu/check-crlf@v1

  coverage:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v3
    - name: Coverage (Twice)
      run: (make coverage || make coverage)
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Report
        path: build/documentation/coverage
    - name: Install rsync
      run: apt install -y rsync
    - name: Deploy coverage to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        name: Coverage Report
        branch: documentation
        folder: build/documentation/coverage
        target-folder: coverage
  
  doxygen:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v3
    - name: Doxygen
      run: make doxygen_generate
    - name: Install rsync
      run: apt install -y rsync
    - name: Upload Doxygen Documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        name: Doxygen Documentation
        branch: documentation
        folder: build/documentation/doxygen/html
        target-folder: doxygen
  
  deploy:
    runs-on: ubuntu-latest
    needs:
    - coverage
    - doxygen

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_branch: documentation
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./