name: Build, Test, and Lint
on:
  push:
    branches: [ "refractor" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build all (Twice)
      run: (make compile || make compile)
  
  test:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v3
    - name: Test (Twice)
      run: (make test || make test)
  
  lint:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v3
    - name: Stylecheck
      run: make google_stylecheck
    - name: Test Stylecheck
      run: make google_stylecheck_test
    - name: Line Endings
      uses: erclu/check-crlf@v1

  coverage:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v3
    - name: Coverage (Twice)
      run: (make coverage || make coverage)
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Report
        path: build/documentation/coverage
  
  documentation:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    needs: [build, lint, coverage]
    steps:
    - uses: actions/checkout@v3
    - name: make coverage
      run: make coverage
    - name: Doxygen
      run: make doxygen_generate
    - name: Install rsync
      run: apt install -y rsync
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/documentation

  deploy:
    needs: [documentation]

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4