name: Build, Test, and Lint
on:
  push:
    branches: [ "refractor" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v4
    - name: Build all (Twice)
      run: (make compile || make compile)
  
  test:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest

    steps:
    - uses: actions/checkout@v4
    - name: Test (Twice)
      run: (make test || make test)
  
  lint:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v4
    - name: Stylecheck
      run: make google_stylecheck
    - name: Test Stylecheck
      run: make google_stylecheck_test
    - name: Line Endings
      uses: erclu/check-crlf@v1

  coverage:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    steps:
    - uses: actions/checkout@v4
    - name: Coverage (Twice)
      run: (make coverage || make coverage)
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: build/documentation/coverage
  
  documentation:
    runs-on: ubuntu-latest
    container: nguy8tri/huskysat:latest
    needs: [build, lint, coverage]
    steps:
    - uses: actions/checkout@v4
    - name: make coverage
      run: make coverage
    - name: Doxygen
      run: make doxygen_generate
    - name: Install rsync
      run: apt install -y rsync
    - name: Upload Pages Artifact
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        name: Documentation
        branch: documentation
        path: build/documentation
  
  documentation-upload:
    needs: documentation
    # steps:
    # - uses: actions/checkout@v4
    #   with:
    #     ref: documentation
    # - name: Build with Jekyll
    #   uses: actions/jekyll-build-pages@v1
    #   with:
    #     source: .
    #     destination: ./_site
    #     verbose: true
    # - name: Upload Pages Artifact
    #   with:
    #     path: ./_site
    #     name: github-pages
    #     retention-days: 1

  documentation-deploy:
    needs: documentation-upload

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4