name: GitHub Pages Deployment
on:
  push:
    branches:
      - documentation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages using Bot
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_branch: documentation
        publish_dir: ./
