name: Update PR Description with Build Artifacts

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, synchronize]

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR number
        id: get-pr-number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Update PR description
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = process.env.PR_NUMBER;
            prFooter = `# Artifacts for PR #${prNumber}\n\n`;
            prFooter += `- [Coverage Artifact](https://uwcubesat.github.io/found/${prNumber}/merge/coverage)\n`;
            prFooter += `- [Doxygen Artifact](https://uwcubesat.github.io/found/${prNumber}/merge/doxygen)\n`;
            
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            console.log("Body: ${pr.body}");
            console.log("Footer: ${prFooter}");
            console.log("pr.body.includes(prFooter): ${pr.body.includes(prFooter)}")

            if (pr.body.includes(prFooter)) {
              console.log('PR description already has documentation artifacts');
            } else {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                body: `# PR Description\n\n${pr.body}\n${prFooter}`,
              });
              console.log('PR description updated with documentation artifacts');
            }
